### ISSUE TITLE
Add more info to the readme of of project 2 and 3

### ISSUE THREAD

**Issue by praistarr** [OSCA-Ado-Ekiti/Hacktoberfest-2023-Ekiti-DSN#6]

**Comment by KaneshiroKeola** [comment]
Can i help to add information to your readme projects?

**Comment by praistarr** [comment]
Yes, I've assigned it to you

**Comment by KaneshiroKeola** [comment]
I have completed updating/ adding extra info to both projects 2 and 3.

**Comment by praistarr** [comment]
Thank you

**Comment by praistarr** [comment]
The repo has been excluded from hacktoberfest and a new repo has been created. You can find it here: https://github.com/OSCA-Ado-Ekiti/Hacktoberfest-Ekiti-Disease-Classifier
